var GU_iPad=GU_iPad||{};
GU_iPad.Utilities={hasClass:function(b,a){return b.className.match(RegExp("(\\s|^)"+a+"(\\s|$)"))},addClass:function(b,a){this.hasClass(b,a)||(b.className+=" "+a)},removeClass:function(b,a){if(this.hasClass(b,a))b.className=b.className.replace(RegExp("(\\s|^)"+a+"(\\s|$)"),"")},addLoadEvent:function(b){var a=window.onload;window.onload=typeof window.onload!="function"?b:function(){a&&a();b()}},dontMove:function(){},addScrollPane:function(b,a){YUI().use("scrollview-base",function(c){(new c.ScrollView({srcNode:"#"+b,
height:a,flick:{minDistance:10,minVelocity:0.3,axis:"y"}})).render()})}};if(typeof Object.create!=="function")Object.create=function(b){function a(){}a.prototype=b;return new a};GU_iPad=GU_iPad||{};
GU_iPad.Ad={_dimensions_array:{oneByOne:[172,172],threeByFour:[702,956],oneByTwo:[172,418],twoByOne:[418,172],threeByOne:[664,172],landscape:[1024,768],portrait:[768,1024]},_trackingCode:0,_campaignID:0,_size:[],_type:"",_background:"",_node:null,_stack:{},_layers:[],_activeLayer:null,init:null,setSize:function(b){this._size=this._dimensions_array[b];this._dimensions=b},getSize:function(){return this._size},getWidth:function(){return this._size[0]},getHeight:function(){return this._size[1]},getDimensions:function(){return this._dimensions},
setTrackingCode:function(b){this._trackingCode=b},getTrackingCode:function(){return this._trackingCode},setCampaignID:function(b){this._campaignID=b},getCampaignID:function(){if(this._campaignID==="%%CAMP%%")this._campaignID="test-id";return this._campaignID},setType:function(b){this._type=b},getType:function(){return this._type},createDefaultNode:function(b){b===void 0&&(b=!0);var a;this._node=document.createElement("div");this._node.setAttribute("size",this.getDimensions());this._node.setAttribute("format",
this.getType());this._node.className="ad";this._node.id=this.getCampaignID();var c=document.createElement("div");c.className="wrap";this._node.appendChild(c);var d=this.getStack(),e=50,f;for(f in d)d[f].name=f,a=new GU_iPad.Ad.Layer(d[f],this,e),c.appendChild(a.getNode()),this.getLayers().push(a),b?e-=1:e+=1;this.setActiveLayer(this.getLayers()[0])},getNode:function(){return this._node},setActiveLayer:function(b){this._activeLayer=b},getActiveLayer:function(){return this._activeLayer},setBackground:function(b){this._background=
b},getBackground:function(){return this._background},applyBackground:function(b){b!=""&&this.getNode().setAttribute("style","background: url("+b+") no-repeat")},setStack:function(b){this._stack=b},getStack:function(){return this._stack},setLayers:function(b){this._layers=b},getLayers:function(){return this._layers},setDefault:function(b,a){this.setSize(b.size);this.setType(b.type);this.setBackground(b.background);this.setCampaignID(b.campaignID);this.setTrackingCode(b.trackingCode);this.setStack(b.stack);
this.init=a},insert:function(){var b=this.getNode();document.body.appendChild(b);this.applyBackground(this.getBackground())},trackAction:function(b,a){typeof a==="undefined"&&(a="");var c="gceadtracking-"+this.getCampaignID()+"://"+b+"/"+a;try{var d=new XMLHttpRequest;d.open("GET",c,!0);d.send(null)}catch(e){}},switchLayer:function(b){this.getActiveLayer().setLayerZIndex();this.setActiveLayer(this.getLayers()[b-1]);this.trackAction("switch-layer",this.getActiveLayer().name);this.getActiveLayer().makeActive()}};
GU_iPad.Ad.Layer=function(b,a,c){this._active=!1;this._zIndex=c;if(b.name)this.name=b.name;this._media=b.media;this._node=document.createElement("div");this.create(b.hotspots,a);this.setLayerZIndex()};
GU_iPad.Ad.Layer.prototype.create=function(b,a){if(this._media.type=="image")this._node.innerHTML='<img src="'+this._media.reference+'" width="'+a.getWidth()+'" height="'+a.getHeight()+'" alt="" />';else if(this._media.type=="video")this._node.innerHTML='<video src="'+this._media.reference+'" controls="controls" type="'+this._media.format+'"></video>';var c,d;for(d in b)c=new GU_iPad.Ad.Hotspot(b[d],a),this._node.appendChild(c.init());this._node.className="layer"};
GU_iPad.Ad.Layer.prototype.getNode=function(){return this._node};GU_iPad.Ad.Layer.prototype.makeActive=function(){GU_iPad.Utilities.addClass(this.getNode(),"active")};GU_iPad.Ad.Layer.prototype.setLayerZIndex=function(){this.getNode().style.zIndex=this._zIndex;GU_iPad.Utilities.removeClass(this.getNode(),"active")};
GU_iPad.Ad.Hotspot=function(b,a){this._parentAd=a;if(b.targetLayer)this._targetType="layer",this._target=b.targetLayer;else if(b.targetURL||b.targetAd)this._targetType="url",this._target=b.targetURL||"#";this._top=b.top||0;this._left=b.left||0;this._width=b.width||this._parentAd.getWidth();this._height=b.height||this._parentAd.getHeight();this._node=null;var c=this;this.init=function(){this.createNode();return this.getNode()};this.touchHotspotHandler=function(a){a.preventDefault();c.touchHotspot()}};
GU_iPad.Ad.Hotspot.prototype.createNode=function(){this._node=document.createElement("a");this._node.className="hotspot";this._node.setAttribute("style","width: "+this._width+"px; height: "+this._height+"px; top: "+this._top+"px; left: "+this._left+"px;");this._targetType==="layer"?(this._node.href="#",this._node.addEventListener("click",this.touchHotspotHandler,!1)):this._node.href=this.getTarget()};GU_iPad.Ad.Hotspot.prototype.getNode=function(){return this._node};
GU_iPad.Ad.Hotspot.prototype.getTarget=function(){return this._target.toString()};GU_iPad.Ad.Hotspot.prototype.touchHotspot=function(){this.getParentAd().switchLayer(this.getTarget())};GU_iPad.Ad.Hotspot.prototype.getParentAd=function(){return this._parentAd};GU_iPad.DefaultAd=function(b){var a=Object.create(GU_iPad.Ad);a.setDefault(b,function(){this.createDefaultNode();this.insert()});return a};
GU_iPad.SlideAd=function(b){var a=Object.create(GU_iPad.Ad);a.vertical=b.vertical;a.createSlideNode=function(){this._node=document.createElement("div");this._node.setAttribute("size",this.getDimensions());this._node.setAttribute("format",this.getType());this._node.className="ad";this._node.id=this.getCampaignID();this._node.innerHTML=this.getMarkup()};a.getMarkup=function(){var a,b="",e=this.getStack();b+='<div class="carousel" size="'+this.getDimensions()+'">';b+='<ul id="carousel-'+this.getCampaignID()+
'">';for(var f in e)a=new GU_iPad.Ad.Layer(e[f],this),b+='<li data-name="'+f+'">',b+=a.getNode().innerHTML,b+="</li>",this.getLayers().push(a);b+="</ul></div>";return b};a.setDefault(b,function(){this.createSlideNode();this.insert();var a=this;this.carousel=new GU_iPad.Carousel("carousel-"+this.getCampaignID(),{vertical:this.vertical,tracker:function(b,e){return a.trackAction.apply(a,[b,e])}});this.carousel.init()});return a};
GU_iPad.FlipAd=function(b){var a=Object.create(GU_iPad.Ad);a.setDefault(b,function(){this.createDefaultNode();this.insert();this.addClasses();this.bindEvents()});a.addClasses=function(){var a=this.getLayers()[0].getNode(),b=this.getLayers()[1].getNode();GU_iPad.Utilities.addClass(a,"ad-front");GU_iPad.Utilities.addClass(b,"ad-back")};a.bindEvents=function(){this.getNode().addEventListener("click",a.tapped,!1)};a.tapped=function(a){a.target.nodeName.toLowerCase()=="a"&&a.target.getAttribute("href")==
"#"&&(GU_iPad.Utilities.hasClass(this,"show")?GU_iPad.Utilities.removeClass(this,"show"):GU_iPad.Utilities.addClass(this,"show"))};return a};
GU_iPad.ZoomAd=function(b){var a=Object.create(GU_iPad.Ad);a.zoomed=!1;a.initialZoomLayerSize=b.initialZoomLayerSize;a.setDefault(b,function(){this.createDefaultNode(!1);this.insert();this.bindEvents();GU_iPad.Utilities.addClass(this.getNode(),"zoom-in");this.zoomed=!0});a.bindEvents=function(){this.getNode().addEventListener("click",a.tapped,!1)};a.tapped=function(){a.zoomed===!1?(a.trackAction("zoom-in"),GU_iPad.Utilities.removeClass(this,"zoom-out"),GU_iPad.Utilities.addClass(this,"zoom-in"),a.zoomed=
!0):(a.trackAction("zoom-out"),GU_iPad.Utilities.removeClass(this,"zoom-in"),GU_iPad.Utilities.addClass(this,"zoom-out"),a.zoomed=!1)};return a};GU_iPad.MultiAd=function(b){var a=Object.create(GU_iPad.Ad),c=b.ads,d=b.positions;self=a;a.setDefault(b,function(){this.createDefaultNode();this.insert();for(var a in c)x=new GU_iPad.AdFactory(c[a]),x.getNode().style.top=d[a].top+"px",x.getNode().style.left=d[a].left+"px"});return a};
GU_iPad.RotateAd=function(b){b.size=Math.abs(window.orientation)===90?"landscape":"portrait";var a=Object.create(GU_iPad.Ad);a.addClasses=function(){var a=this.getLayers()[0].getNode(),b=this.getLayers()[1].getNode();GU_iPad.Utilities.addClass(a,"portrait");GU_iPad.Utilities.addClass(b,"landscape");a=b.getElementsByTagName("img")[0];a.width=1024;a.height=768};a.setDefault(b,function(){this.createDefaultNode();this.insert();this.addClasses();var b=this.getNode();change_orientation=function(){a.getDimensions()===
"portrait"?(a.setSize("landscape"),b.setAttribute("size","landscape")):(a.setSize("portrait"),b.setAttribute("size","portrait"));console.log(a.getDimensions())};console.log(a.getDimensions());window.onorientationchange=function(a){change_orientation();a.preventDefault()};change_orientation()});return a};
GU_iPad.AdFactory=function(b){var a;switch(b.type){case "multi":a=new GU_iPad.MultiAd(b);a.init();break;case "rotate":a=new GU_iPad.RotateAd(b);a.init();break;case "zoom":a=new GU_iPad.ZoomAd(b);a.init();break;case "flip":a=new GU_iPad.FlipAd(b);a.init();break;case "curl":a=new GU_iPad.FlipAd(b);a.init();break;case "slide":a=new GU_iPad.SlideAd(b);a.init();break;case "default":a=new GU_iPad.DefaultAd(b),a.init()}return a};
GU_iPad.jsonRequest=function(b){var a=new XMLHttpRequest;if(a)a.onreadystatechange=function(){if(a.readyState==4&&(a.status==200||a.status==304)){var b=eval("("+a.responseText+")");GU_iPad.initialiseAds(b)}},a.open("GET",b,!0),a.send(null)};GU_iPad.Utilities.addLoadEvent(function(){GU_iPad.adJson&&GU_iPad.AdFactory(GU_iPad.adJson)});GU_iPad=GU_iPad||{};
GU_iPad.Carousel=function(b,a){this.carousel=null;this.currentIndex=this.currentPosition=this.height=this.width=this.count=0;this.forward=!0;this.options={};var c=this;this.touchEndHandler=function(a){a.target.nodeName.toLowerCase()!="a"&&c.touchEnd(a)};this.init=function(){this.carousel=document.getElementById(b);this.options={vertical:a.vertical||!1};this.tracker=a.tracker||!1;if(this.carousel.nodeName.toLowerCase()=="ul")this.count=this.carousel.getElementsByTagName("li").length,this.options.vertical?
(GU_iPad.Utilities.addClass(this.carousel,"vertical"),this.height=this.carousel.offsetHeight/this.count):(this.carousel.setAttribute("style","width:"+this.carousel.offsetWidth*this.count+"px;"),this.width=this.carousel.offsetWidth/this.count),this.carousel.addEventListener("click",this.touchEndHandler,!1)}};GU_iPad.Carousel.prototype.touchEnd=function(){this.getTarget();this.snapToTarget()};
GU_iPad.Carousel.prototype.getTarget=function(){var b=this.currentIndex==this.count-1?!0:!1,a=this.currentIndex==0?!0:!1;if(this.forward&&!b||a){if(a)this.forward=!0;this.currentIndex++;this.fireTracker("slide-next")}else if(b||!this.forward){if(b)this.forward=!1;this.currentIndex--;this.fireTracker("slide-prev")}};
GU_iPad.Carousel.prototype.fireTracker=function(b){if(this.tracker){for(var a=this.carousel.childNodes[this.currentIndex].attributes,c=null,d=a.length-1;d>=0;--d)if(a[d].name==="data-name")c=a[d].nodeValue;this.tracker(b,c)}};GU_iPad.Carousel.prototype.getCssStyle=function(b){this.options.vertical?this.getCssStyle=function(a){return"translate3d(0, "+a+"px, 0)"}:this.getCssStyle=function(a){return"translate3d("+a+"px, 0, 0)"};return this.getCssStyle(b)};
GU_iPad.Carousel.prototype.setCurrentPosition=function(){this.options.vertical?this.setCurrentPosition=function(){this.currentPosition=-1*this.currentIndex*this.height}:this.setCurrentPosition=function(){this.currentPosition=-1*this.currentIndex*this.width};return this.setCurrentPosition()};GU_iPad.Carousel.prototype.snapToTarget=function(){this.setCurrentPosition();this.carousel.style.webkitTransform=this.getCssStyle(this.currentPosition);this.carousel.style.webkitTransition="300ms ease-out"};
